# fly.toml app configuration file generated for todos-aged-star-8389 on 2025-01-17T14:53:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todos-aged-star-8389'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
